#ifndef PERIMETER_PROTOTYPES_H_
#define PERIMETER_PROTOTYPES_H_

void PERIMETER_CIRCLE();
void PERIMETER_TRIANGLE();
void PERIMETER_SQUARE();
void PERIMETER_RECTANGLE();
void PERIMETER_PENTAGON();
void PERIMETER_HEXAGON();
void PERIMETER_OCTAGON();

#endif