#ifndef VOLUME_PROTOTYPES_H_
#define VOLUME_PROTOTYPES_H_

void VOLUME_SPHERE();
void VOLUME_CYLINDER();
void VOLUME_CUBE();
void VOLUME_REGULAR_TRIANGLULAR_PRISMS();
void VOLUME_REGULAR_RECTANGULAR_PRISMS();
void VOLUME_CONES();

#endif